"""Render a CIS audit report as a self-contained, shareable HTML scorecard.

The output is a single HTML string with inline CSS (no external assets), so it
can be emailed, committed, or handed to a client as-is - the "looks like a
product" artifact an MSP delivers after an audit.
"""

import html

from .cis import PASS, FAIL, UNKNOWN

_STATUS_STYLE = {
    PASS: ("PASS", "#1a7f37", "#e6f4ea"),
    FAIL: ("FAIL", "#b42318", "#fce8e6"),
    UNKNOWN: ("N/A", "#6c737f", "#eef0f2"),
}

_GRADE_COLOR = {
    "A": "#1a7f37",
    "B": "#3d8b40",
    "C": "#b7791f",
    "D": "#c05621",
    "F": "#b42318",
    "N/A": "#6c737f",
}


def render_html(report, title="macOS CIS Benchmark Audit", generated_at=None) -> str:
    """Return a complete HTML document for an audit ``report`` dict."""
    s = report["summary"]
    score = s["compliance_score"]
    grade = s["grade"]
    score_text = "N/A" if score is None else f"{score}%"
    grade_color = _GRADE_COLOR.get(grade, "#6c737f")
    subtitle = html.escape(generated_at) if generated_at else ""

    rows = []
    for r in report["results"]:
        label, fg, bg = _STATUS_STYLE[r["status"]]
        badge = f'<span class="badge" style="color:{fg};background:{bg}">{label}</span>'
        remediation = ""
        if r["status"] == FAIL and r.get("remediation"):
            remediation = (
                f'<div class="fix"><strong>Fix:</strong> '
                f'{html.escape(r["remediation"])}</div>'
            )
        rows.append(
            "<tr>"
            f'<td class="status">{badge}</td>'
            f'<td class="cis">{html.escape(r["cis_id"])}</td>'
            f'<td class="ctrl">{html.escape(r["title"])}{remediation}</td>'
            f'<td class="level">L{r["level"]}</td>'
            "</tr>"
        )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         margin: 0; padding: 2rem; background: #f6f7f9; color: #1a1a1a; }}
  .card {{ max-width: 860px; margin: 0 auto; background: #fff; border-radius: 12px;
          box-shadow: 0 1px 3px rgba(0,0,0,.1); overflow: hidden; }}
  header {{ padding: 1.5rem 2rem; border-bottom: 1px solid #eaecef;
           display: flex; align-items: center; justify-content: space-between; gap: 1rem; }}
  header h1 {{ font-size: 1.25rem; margin: 0; }}
  header .sub {{ color: #6c737f; font-size: .85rem; margin-top: .25rem; }}
  .score {{ text-align: center; min-width: 120px; }}
  .score .grade {{ font-size: 2.5rem; font-weight: 700; line-height: 1;
                  color: {grade_color}; }}
  .score .pct {{ font-size: 1rem; color: #6c737f; }}
  .tallies {{ display: flex; gap: 1rem; padding: 1rem 2rem; border-bottom: 1px solid #eaecef;
             font-size: .9rem; }}
  .tallies span {{ font-weight: 600; }}
  table {{ width: 100%; border-collapse: collapse; }}
  td {{ padding: .75rem 2rem; border-bottom: 1px solid #f0f1f3; vertical-align: top; }}
  td.status {{ width: 64px; }}
  td.cis {{ width: 70px; color: #6c737f; font-variant-numeric: tabular-nums; }}
  td.level {{ width: 40px; color: #6c737f; text-align: right; }}
  .badge {{ display: inline-block; padding: .15rem .5rem; border-radius: 999px;
           font-size: .72rem; font-weight: 700; letter-spacing: .03em; }}
  .fix {{ margin-top: .4rem; font-size: .82rem; color: #57606a; }}
  footer {{ padding: 1rem 2rem; color: #8b949e; font-size: .78rem; text-align: center; }}
  @media (prefers-color-scheme: dark) {{
    body {{ background: #0d1117; color: #e6edf3; }}
    .card {{ background: #161b22; box-shadow: none; border: 1px solid #30363d; }}
    header, .tallies, td {{ border-color: #21262d; }}
    .score .pct, td.cis, td.level, .fix, header .sub {{ color: #8b949e; }}
  }}
</style>
</head>
<body>
  <div class="card">
    <header>
      <div>
        <h1>{html.escape(title)}</h1>
        <div class="sub">{subtitle}</div>
      </div>
      <div class="score">
        <div class="grade">{html.escape(grade)}</div>
        <div class="pct">{score_text}</div>
      </div>
    </header>
    <div class="tallies">
      <div>Passed <span style="color:#1a7f37">{s['passed']}</span></div>
      <div>Failed <span style="color:#b42318">{s['failed']}</span></div>
      <div>Unknown <span style="color:#6c737f">{s['unknown']}</span></div>
      <div>Total <span>{s['total']}</span></div>
    </div>
    <table>
      <tbody>
        {"".join(rows)}
      </tbody>
    </table>
    <footer>
      Generated by macos-fingerprint. Pragmatic subset of the CIS Apple macOS
      Benchmark; not a certified assessment.
    </footer>
  </div>
</body>
</html>
"""
